parameters:
    # Form handlers
    innova_activity.form.handler.activity.class:          Innova\ActivityBundle\Form\Handler\ActivityHandler

    # Form types
    innova_activity.form.type.activity.class:             Innova\ActivityBundle\Form\Type\ActivityType
    innova_activity.form.type.instruction_property.class: Innova\ActivityBundle\Form\Type\ActivityProperty\InstructionPropertyType
    innova_activity.form.type.choice_property.class:      Innova\ActivityBundle\Form\Type\ActivityProperty\ChoicePropertyType

    innova_activity.form.type.multiple_choice_type.class: Innova\ActivityBundle\Form\Type\ActivityType\Choice\MultipleChoiceTypeType
    innova_activity.form.type.unique_choice_type.class:   Innova\ActivityBundle\Form\Type\ActivityType\Choice\UniqueChoiceTypeType
    innova_activity.form.type.boolean_choice_type.class:  Innova\ActivityBundle\Form\Type\ActivityType\Choice\BooleanChoiceTypeType
