services:
    # Activity type
    innova_activity.form.type.activity:
        class: %innova_activity.form.type.activity.class%
        tags:
          - { name: form.type, alias: innova_activity }

    innova_activity.form.type.activity_sequence:
        class: %innova_activity.form.type.activity_sequence.class%
        tags:
          - { name: form.type, alias: innova_activity_sequence }

    # Activity Properties
    innova_activity.form.type.choice_property:
        class: %innova_activity.form.type.choice_property.class%
        tags:
          - { name: form.type, alias: innova_activity_prop_choice }

    innova_activity.form.type.instruction_property:
        class: %innova_activity.form.type.instruction_property.class%
        tags:
          - { name: form.type, alias: innova_activity_prop_instruction }

    innova_activity.form.type.functional_instruction_property:
        class: %innova_activity.form.type.functional_instruction_property.class%
        tags:
          - { name: form.type, alias: innova_activity_prop_functional_instruction }

    innova_activity.form.type.content_property:
        class: %innova_activity.form.type.content_property.class%
        tags:
          - { name: form.type, alias: innova_activity_prop_content }
          
    innova_activity.form.type.multiple_choice_type:
        class: %innova_activity.form.type.multiple_choice_type.class%
        tags:
          - { name: form.type, alias: innova_activity_type_multiple }

    innova_activity.form.type.unique_choice_type:
        class: %innova_activity.form.type.unique_choice_type.class%
        tags:
          - { name: form.type, alias: innova_activity_type_unique }

    innova_activity.form.type.boolean_choice_type:
        class: %innova_activity.form.type.boolean_choice_type.class%
        tags:
          - { name: form.type, alias: innova_activity_type_boolean }